# Generated by Django 4.1.5 on 2023-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
