# Generated by Django 4.1.5 on 2023-07-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Makes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='makes_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField(default=0)),
                ('transmission', models.BooleanField(default=False)),
                ('engine', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid')], default='petrol', max_length=10)),
                ('comments', models.CharField(default='No Seller Comments', max_length=1000)),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.colors')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bodytype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cities')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.makes')),
                ('registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='inventory.cities')),
            ],
        ),
    ]
